# Generated by Django 6.0.1 on 2026-02-19 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybill',
            old_name='amount_paid',
            new_name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dairy_app.monthlybill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
